import "./globals.css";
import AnimalHeader from "./header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en">
        <body>
          <AnimalHeader />
          <section
            className="pt-16"
            style={{ height: "100vh", width: "100%", paddingLeft: "12%" }}
          >
            {children}
          </section>
        </body>
      </html>
    </>
  );
}
